### ISSUE TITLE
nx generate @trumbitta/nx-plugin-openapi:api-spec fails

### ISSUE THREAD

**Issue by haighaj** [trumbitta/nx-trumbitta#34]
I am attempting to use the plugin with the following versions:

- MacOS - 11.4
- Node - v12.22.1
- NPM - 6.14.12
- NX - 12.4.0
- nx-plugin-openapi - 1.4.0

I then completed the following steps:

1. `npx create-nx-workspace --preset=empty`
2. `npm install -D @trumbitta/nx-plugin-openapi`
3. `nx generate @trumbitta/nx-plugin-openapi:api-spec`
4. Using a name of `test-api`
5. Selecting either Yes or no to `create a sample spec file`

I always get the following error:

> Cannot find module '@angular-devkit/schematics'
> Require stack:
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@nrwl/workspace/src/utils/ast-utils.js
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@nrwl/workspace/src/utils/project-type.js
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@nrwl/workspace/index.js
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@trumbitta/nx-plugin-openapi/src/generators/api-spec/generator.js
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@nrwl/tao/src/shared/workspace.js
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@nrwl/tao/src/commands/generate.js
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@nrwl/tao/index.js
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@nrwl/cli/lib/init-local.js
> - /Users/my-account/dev/training/nx/cart-service/node_modules/@nrwl/cli/bin/nx.js
> - /Users/my-account/.nvm/versions/node/v10.22.0/lib/node_modules/nx/node_modules/@nrwl/cli/bin/nx.js
> - /Users/my-account/.nvm/versions/node/v10.22.0/lib/node_modules/nx/bin/nx.js

I can work around the issue by adding the missing `@angular-devkit/schematics` library via `npm i --save-dev @angular-devkit/schematics` but it feels like I shouldn't need to do that

**Comment by trumbitta** [comment]
Hey @haighaj , I just released version 1.5.0 which should 🤞 solve this issue 

https://www.npmjs.com/package/@trumbitta/nx-plugin-openapi

Let me know it works for you!

**Comment by trumbitta** [comment]
I spoke too soon: 1.6.0 doesn't fix it and it's also broken in other ways.

Cooking 1.6.1 right this moment, but the bad news is I ended up adding `@angular-devkit/schematics` as a peer dependency and update installation instructions in the README.

I'll try to get info / help from the Nx team for a future fix :)

**Comment by trumbitta** [comment]
@haighaj ok, 1.5.1 is released and your workaround has become official for now.

`npm install -D @trumbitta/nx-plugin-openapi @angular-devkit/schematics`

and this note in the README:

---- 
## 💡 How to install

```sh
npm install -D @trumbitta/nx-plugin-openapi @angular-devkit/schematics
```

**ℹ️ The `@angular-devkit/schematics` is especially needed if you are installing on a empty workspace!**
----
