### ISSUE TITLE
Feature Request: Add Docker as an option to generate source files

### ISSUE THREAD

**Issue by samdanae** [trumbitta/nx-trumbitta#48]
It would be beneficial to have a Docker option to generate the source files with.

Currently, to use this plugin to its full extent (to generate source files), developers need to install Java. Since the [OpenAPI Generator project](https://openapi-generator.tech/#try) already includes a Docker image to generate source files with, it would be make sense for this plugin to offer that option as well.

**Comment by trumbitta** [comment]
That's a brilliant idea! Do you want to take a shot at it?

Otherwise I don't know when I'll be able to work on it, but it's now definitely on my radar 👍

**Comment by samdanae** [comment]
Cool, thanks. Yes, I'll try it out at some point. Please feel free to assign to me.
