### ISSUE TITLE
Executor never shows openapi-generator-cli output

### ISSUE THREAD

**Issue by JulioC** [trumbitta/nx-trumbitta#67]
When running `generate-api-lib-sources` executor, the `openapi-generator-cli` output is never shown to the user, even when an error happens. This makes it very hard to debug issues with the OpenAPI schema or even with the executor configs.

It would be useful to show the output on error or even consume the verbose flag from executor context. 

Note: the storybook plugin for nx has an `silent` option which hides the build logs output, maybe this could be used instead of the verbose flag

**Comment by youngchen7** [comment]
We were running into this as well, and we frequently had to run `openapi-generator-cli` directly just for debugging purposes.

Here's a PR that logs the command used to invoke `openapi-generator-cli`, as well as forwards the stdout to the nx logger: https://github.com/trumbitta/nx-trumbitta/pull/71

**Comment by trumbitta** [comment]
@all-contributors please add @JulioC for ideas
