### ISSUE TITLE
[bug] Silent property breaks generation

### ISSUE THREAD

**Issue by iceteabottle** [trumbitta/nx-trumbitta#74]
Related to the last PR merge (https://github.com/trumbitta/nx-trumbitta/pull/71) I've found a bug with the brand new `silent` flag. The executor throws an exception if `silent` is set to `true`.

```
 >  NX   Cannot read properties of null (reading 'on')


TypeError: Cannot read properties of null (reading 'on')
    at /Users/username/dev/company/nx-project/node_modules/@trumbitta/nx-plugin-openapi/src/executors/generate-api-lib-sources/executor.js:46:26
    at new Promise (<anonymous>)
    at /Users/username/dev/company/nx-project/node_modules/@trumbitta/nx-plugin-openapi/src/executors/generate-api-lib-sources/executor.js:24:16
    at Generator.next (<anonymous>)
    at /Users/username/dev/company/nx-project/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/username/dev/company/nx-project/node_modules/tslib/tslib.js:113:16)
    at generateSources (/Users/username/dev/company/nx-project/node_modules/@trumbitta/nx-plugin-openapi/src/executors/generate-api-lib-sources/executor.js:22:20)
    at /Users/username/dev/company/nx-project/node_modules/@trumbitta/nx-plugin-openapi/src/executors/generate-api-lib-sources/executor.js:16:15
    at Generator.next (<anonymous>)
```

I got the same exception if I pass the option via config and cli.

PS: To be fair. The rest of the changes of the last PR works fine 🤓

**Comment by youngchen7** [comment]
Oh interesting! I definitely had a test case that set silent to true - I'll have to look into this some more

**Comment by youngchen7** [comment]
Ah I see - if `stdio: 'ignore'` is set node actually doesn't populate stdio or stderr at all - this wasn't caught because spawn was mocked in the unit tests.

https://nodejs.org/api/child_process.html#subprocessstderr

**Comment by youngchen7** [comment]
Here's the fix 😄 https://github.com/trumbitta/nx-trumbitta/pull/76

**Comment by trumbitta** [comment]
@all-contributors please add @iceteabottle for reporting this bug

**Comment by iceteabottle** [comment]
@youngchen7 it works like a charm. Thanks for the fast fix.
